openapi: 3.0.0
info:
  title: "Cubone API"
  description: "Public API for getting data from our database."
  version: "0.1.0"

paths:
  /address/{address}:
    get:
      summary: "Get information about an IP address"
      parameters:
        - $ref: "#/components/parameters/addressParam"
      responses:
        200:
          description: "IP address info"
        400:
          description: "Malformed IP address specified"
        404:
          description: "No record was found for the specified IP address"
  /_unit:
    get:
      summary: "Unit information"
      responses:
        200:
          description: "Object containing information about the unit"
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "5ac09ff9-ab5a-4a33-9d62-387e07b2c99b"
  /_health:
    get:
      summary: "Health status"
      responses:
        200:
          description: "OK"


components:
  parameters:
    addressParam:
      name: address
      in: path
      required: true
      schema:
        type: string
