openapi: 3.0.0
info:
  title: "Diglett API"
  description: "A service that provides a nice HTTP abstraction over services that provide address information via text files."
  version: "0.1.0"

paths:
  /{address}/allocation:
    get:
      summary: "Get the allocation state for the specified address"
      parameters:
        - $ref: "#/components/parameters/addressParam"
      responses:
        200:
          description: "Allocation state (one of Unknown, Reserved, Unallocated, Allocated)"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
        400:
          description: "Bad IP address"
  /{address}/rir:
    get:
      summary: "Get the RIR for the specified address."
      parameters:
        - $ref: "#/components/parameters/addressParam"
        - name: top
          in: query
          schema:
            type: boolean

      responses:
        200:
          description: "RIR name (one of arin, ripencc, apnic, lacnic, afrinic, other) or unknown if no RIR found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
        400:
          description: "Bad IP address"
  /{address}/asn:
    get:
      summary: "Get the ASN for the specified IP address"
      parameters:
        - $ref: "#/components/parameters/addressParam"
      responses:
        200:
          description: "AS number or null if no AS found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
        400:
          description: "Bad IP address"
  /{address}/country:
    get:
      summary: "Get the country code for the specified IP address"
      parameters:
        - $ref: "#/components/parameters/addressParam"
      responses:
        200:
          description: "Country code or null if no country code found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
        400:
          description: "Bad IP address"

components:
  parameters:
    addressParam:
      name: address
      in: path
      required: true
      schema:
        type: string
