# Example config for the CLI
[database]
# hostname = # The host used when connecting to the database.
# username = # The username used when connecting to the database.
# password = # The password used when connecting to the database.
# database = # The target database used when connecting to the database.
