[api]
# port =		# Specifies the port on which the API will listen

[database]
# hostname = 		# The host used when connecting to the database
# username = 	# The username used when connecting to the database
# password = 	# The password used when connecting to the database
# database = 	# The target database used when connecting to the database

[pokedex]
# address =		# The address used when connecting to a Pokedex instance

[unit]
# username =	# The username of the unit, used when logging into Pokedex
# password =	# The password of the unit, used when logging into Pokedex
